# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

P01 <- function(l, r, z, type, theta01_, theta02_, theta12_, gammas01, knots01, gammas02, knots02, gammas12, knots12, boundaries) {
    .Call(`_dcsm_P01`, l, r, z, type, theta01_, theta02_, theta12_, gammas01, knots01, gammas02, knots02, gammas12, knots12, boundaries)
}

