# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name RoystonParmarFns$P01Integrand
#' @title Compute the integrand for the transition probability of progression.
#' @param v A vector of the log times
#' @param l The lower bound of the integral (not logged)
#' @param r The upper bound of the integral (not logged)
#' @param z The vector of patient treatment arms
NULL

P01 <- function(l, r, z, theta01_, theta02_, theta12_, gammas01, knots01, gammas02, knots02, gammas12, knots12, boundaries) {
    .Call(`_dcsm_P01`, l, r, z, theta01_, theta02_, theta12_, gammas01, knots01, gammas02, knots02, gammas12, knots12, boundaries)
}

