# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generic-ish function to compute the 0 \eqn{\to} 1 transition probability
#'
#' @description
#' Typically wrapped by a separate function so that only the first 3 arguments are provided.
#' @param l The lower bounds of the (untransformed) interval
#' @param r The upper bounds of the (untransformed) interval
#' @param z The arms (case/control etc...)
#' @param type A string of either \code{"RoystonParmar"} or \code{"JolyPenalised"}
#' @param theta01_,theta02_,theta12_,gammas01,knots01,gammas02,knots02,gammas12,knots12,boundaries Passed to the \link{IllnessDeath} constructors to create the relevant set of functions.
#' @details
#' If \code{type = "RoystonParmar"} is used then a transformed interval with the substitution \eqn{u = exp(v)} is used to avoid a discontinuity at 0.
#' This then becomes an infinite integral.
P01 <- function(l, r, z, type, theta01_, theta02_, theta12_, gammas01, knots01, gammas02, knots02, gammas12, knots12, boundaries) {
    .Call(`_dcsm_P01`, l, r, z, type, theta01_, theta02_, theta12_, gammas01, knots01, gammas02, knots02, gammas12, knots12, boundaries)
}

